/**
 * Dish / offer / gallery imagery.
 *
 * Renders the illustration files in `public/Images` (generated by
 * `scripts/generate-images.mjs`). These are hand-authored flat-vector
 * illustrations, not photography — swap the files for real photos of the actual
 * food when available, keeping the same filenames, and nothing here changes.
 *
 * Deliberately a plain <img> rather than next/image: the sources are local static
 * SVGs, and routing SVG through the Next image optimizer requires
 * `dangerouslyAllowSVG`, which we don't want to enable globally. Vector art gains
 * nothing from raster optimization anyway.
 *
 * `tint` still renders as the container background so there is no white flash
 * before the illustration paints, and it remains the fallback if a file is missing.
 */

interface DishImageProps {
  src: string;
  tint: string;
  alt: string;
  className?: string;
  rounded?: string;
  priority?: boolean;
  /** Focal sizing for the illustration inside its frame. */
  fit?: "cover" | "contain";
}

export function DishImage({
  src,
  tint,
  alt,
  className = "",
  rounded = "rounded-xl",
  priority = false,
  fit = "cover",
}: DishImageProps) {
  return (
    <div
      className={`relative overflow-hidden bg-gradient-to-br ${tint} ${rounded} ${className}`}
    >
      <img
        src={src}
        alt={alt}
        loading={priority ? "eager" : "lazy"}
        decoding="async"
        draggable={false}
        className={`absolute inset-0 h-full w-full ${
          fit === "cover" ? "object-cover" : "object-contain"
        }`}
      />
    </div>
  );
}

/** Green square = veg, red = non-veg. Standard Indian FSSAI marking. */
export function VegBadge({ isVeg }: { isVeg: boolean }) {
  const label = isVeg ? "Vegetarian" : "Non-vegetarian";
  return (
    <span
      title={label}
      aria-label={label}
      className={`flex h-4 w-4 items-center justify-center rounded-sm border-2 bg-white ${
        isVeg ? "border-green-600" : "border-red-600"
      }`}
    >
      <span
        aria-hidden="true"
        className={`h-2 w-2 rounded-full ${isVeg ? "bg-green-600" : "bg-red-600"}`}
      />
    </span>
  );
}
